name: Ubuntu 22.04 (x64) Server Configuration Check

on:
  workflow_dispatch:

jobs:
  check_config_ubuntu_2204_x64:
    runs-on: ubuntu-22.04
    steps:
      - name: Display Server Configuration
        shell: bash
        run: |
          echo -e "\nServer Configuration:"
          echo "--------------------------------------------------"
          cpu_name=$(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2- | sed 's/^ *//')
          cores=$(grep -c ^processor /proc/cpuinfo)
          threads=$cores
          ghz=$(awk -F: '/cpu MHz/ {print $2; exit}' /proc/cpuinfo | awk '{printf "%.2f", $1/1000}' 2>/dev/null || echo "N/A")
          gpu_names=$(lspci 2>/dev/null | grep -i 'vga\|3d\|2d' | cut -d: -f3- | xargs | sed 's/ \[/\n\[/g' | paste -sd', ' -)
          ram_bytes=$(grep MemTotal /proc/meminfo | awk '{print $2 * 1024}')
          ram_gb=$(awk -v b="$ram_bytes" 'BEGIN {printf "%.1f", b/1024/1024/1024}')
          ram_mb=$(awk -v b="$ram_bytes" 'BEGIN {printf "%.1f", b/1024/1024}')
          ram_human="$ram_gb GB ($ram_mb MB)"
          os=$(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '"')
          ip4=$(curl -s --max-time 3 https://ipv4.seeip.org)
          ip6=$(curl -s --max-time 3 https://ipv6.seeip.org)
          echo "CPU: ${cpu_name:-N/A}, $cores cores, $threads threads, ~$ghz GHz"
          echo "GPU: ${gpu_names:-Not detected or N/A}"
          echo "RAM: $ram_human"
          echo "Operating System: $os"
          [[ -n "$ip4" ]] && echo "IP v4: $ip4"
          [[ -n "$ip6" ]] && echo "IP v6: $ip6"
          [[ -z "$ip4" && -z "$ip6" ]] && echo "Could not retrieve external IP address. Does the server have network connectivity?"
          echo "--------------------------------------------------"